// Re-export generated Zod schemas (Prisma-free)
// These are generated by prisma-zod-generator from packages/db (MongoDB)
import { z } from 'zod';

// Pure model schemas (for validation of complete models) - MongoDB
export * from './generated/schemas/variants/pure/index';
export type { UserPureType } from './generated/schemas/variants/pure/User.pure';
export type { SessionPureType } from './generated/schemas/variants/pure/Session.pure';

// Input schemas (for validation of input data) - MongoDB
export * from './generated/schemas/variants/input/index';
export type { UserInputType } from './generated/schemas/variants/input/User.input';
export type { SessionInputType } from './generated/schemas/variants/input/Session.input';

// PostgreSQL schemas (from packages/db-postgres)
// Exported under 'postgres' namespace to differentiate from MongoDB schemas
export * as postgres from './generated/postgres/schemas/variants/pure/index';
export * as postgresInput from './generated/postgres/schemas/variants/input/index';

// === Auth Validation Schemas ===

/**
 * Common passwords blocklist (subset - extend as needed).
 * Based on OWASP recommendations.
 */
const BLOCKED_PASSWORDS = new Set([
  'password1234',
  'password12345',
  'qwerty123456',
  '123456789012',
  'admin1234567',
]);

/**
 * Signup input validation schema.
 * - email: valid email format, required
 * - name: non-empty string (1-100 chars), required
 * - password: 12-64 characters per NIST SP 800-63B-4, required
 */
export const SignupInputSchema = z.object({
  email: z.string().email('Invalid email format').toLowerCase(),
  name: z.string().min(1, 'Name is required').max(100, 'Name must be 100 characters or less'),
  password: z
    .string()
    .min(12, 'Password must be at least 12 characters')
    .max(64, 'Password must be at most 64 characters')
    .refine(
      (pwd) => !BLOCKED_PASSWORDS.has(pwd.toLowerCase()),
      'This password is too common. Please choose a more unique password.'
    ),
});

export type SignupInput = z.infer<typeof SignupInputSchema>;

/**
 * Login input validation schema.
 * - email: valid email format, required
 * - password: non-empty string, required
 */
export const LoginInputSchema = z.object({
  email: z.string().email('Invalid email format'),
  password: z.string().min(1, 'Password is required'),
});

export type LoginInput = z.infer<typeof LoginInputSchema>;

/**
 * Refresh token input validation schema.
 * - refreshToken: non-empty string, required
 */
export const RefreshTokenInputSchema = z.object({
  refreshToken: z.string().min(1, 'Refresh token is required'),
});

export type RefreshTokenInput = z.infer<typeof RefreshTokenInputSchema>;

// === Weather Validation Schemas ===

/**
 * Weather location from IP geolocation.
 */
export const WeatherLocationSchema = z.object({
  city: z.string(),
  region: z.string(),
  country: z.string(),
  latitude: z.number(),
  longitude: z.number(),
});

export type WeatherLocation = z.infer<typeof WeatherLocationSchema>;

/**
 * Weather condition details.
 */
export const WeatherConditionSchema = z.object({
  main: z.string(),
  description: z.string(),
  icon: z.string(),
});

export type WeatherCondition = z.infer<typeof WeatherConditionSchema>;

/**
 * Complete weather response.
 */
export const WeatherDataSchema = z.object({
  location: WeatherLocationSchema,
  temperature: z.number(),
  feelsLike: z.number(),
  humidity: z.number().int().min(0).max(100),
  pressure: z.number().int(),
  windSpeed: z.number(),
  windDirection: z.number().int(),
  visibility: z.number().int(),
  condition: WeatherConditionSchema,
  sunrise: z.date(),
  sunset: z.date(),
  fetchedAt: z.date(),
});

export type WeatherData = z.infer<typeof WeatherDataSchema>;

// === QF Simulation Validation Schemas ===

/**
 * Round status enum.
 */
export const RoundStatusSchema = z.enum(['setup', 'voting', 'closed']);
export type RoundStatus = z.infer<typeof RoundStatusSchema>;

/**
 * Create round input.
 */
export const CreateRoundInputSchema = z.object({
  name: z.string().min(1, 'Round name is required').max(100),
  matchingPool: z.number().positive('Matching pool must be positive'),
  voterBudget: z.number().positive('Voter budget must be positive'),
});
export type CreateRoundInput = z.infer<typeof CreateRoundInputSchema>;

/**
 * Add project input.
 */
export const AddProjectInputSchema = z.object({
  name: z.string().min(1, 'Project name is required').max(100),
  description: z.string().max(500).default(''),
});
export type AddProjectInput = z.infer<typeof AddProjectInputSchema>;

/**
 * Generate voter codes input.
 */
export const GenerateCodesInputSchema = z.object({
  count: z.number().int().min(1).max(100, 'Maximum 100 codes at a time'),
});
export type GenerateCodesInput = z.infer<typeof GenerateCodesInputSchema>;

/**
 * Submit vote input.
 */
export const SubmitVoteInputSchema = z.object({
  voterCode: z.string().min(1, 'Voter code is required'),
  allocations: z.record(z.string(), z.number().nonnegative()),
});
export type SubmitVoteInput = z.infer<typeof SubmitVoteInputSchema>;

/**
 * Preview vote input (for live matching preview).
 */
export const PreviewVoteInputSchema = z.object({
  allocations: z.record(z.string(), z.number().nonnegative()),
});
export type PreviewVoteInput = z.infer<typeof PreviewVoteInputSchema>;
